### PR TITLE
Since gardener node agent, docker is not required anymore

### PR DESCRIPTION
**Pull request by majst01**
## Description

All our deployed clusters have gardener node agent instead of cloud-config-downloader. This removes the hard requirement for docker to make bootstrapping possible.

Install containerd only.

Closes: #106

### CODE REVIEW

**Review by robertvolkmann — CHANGES_REQUESTED** [review]
You downgrade containerd from 1.7.22 to 1.6.20 because you switched from `containerd.io` (Docker repository) to  `containerd` (Debian repository).

Reproduce by:
```bash
$ docker run -it debian:bookworm
$ apt update
$ apt install --yes ca-certificates curl gnupg2
$ curl -fLsS https://download.docker.com/linux/debian/gpg | apt-key add -
$ echo "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
$ apt update
$ apt info containerd
Package: containerd
Version: 1.6.20~ds1-1+b1
$ apt info runc
Package: runc
Version: 1.1.5+ds1-1+deb12u1
$ apt info docker-ce
Package: docker-ce
Version: 5:27.3.1-1~debian.12~bookworm
Priority: optional
Section: admin
Maintainer: Docker <support@docker.com>
Installed-Size: 111 MB
Depends: containerd.io (>= 1.6.24), docker-ce-cli, iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.34), libsystemd0
Recommends: apparmor, ca-certificates, docker-ce-rootless-extras, git, libltdl7, pigz, procps, xz-utils
Suggests: aufs-tools, cgroupfs-mount | cgroup-lite
$ apt info containerd.io
Package: containerd.io
Version: 1.7.22-1
```

**Comment by robertvolkmann** [comment]
Similar situation with Ubuntu:
```bash
$ docker run -it ubuntu:24.04
$ apt update
$ apt install --yes ca-certificates curl gnupg2
$ curl -fLsS https://download.docker.com/linux/ubuntu/gpg | apt-key add -
$ echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
$ apt update
$ apt info containerd
Package: containerd
Version: 1.7.12-0ubuntu4.1
$ apt info runc
Package: runc
Version: 1.1.12-0ubuntu3.1
$ apt info docker-ce
Package: docker-ce
Version: 5:27.3.1-1~ubuntu.24.04~noble
Priority: optional
Section: admin
Maintainer: Docker <support@docker.com>
Installed-Size: 111 MB
Depends: containerd.io (>= 1.6.24), docker-ce-cli, iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.34), libsystemd0
Recommends: apparmor, ca-certificates, docker-ce-rootless-extras, git, libltdl7, pigz, procps, xz-utils
Suggests: aufs-tools, cgroupfs-mount | cgroup-lite
$ apt info containerd.io
Package: containerd.io
Version: 1.7.22-1
```

**Comment by majst01** [comment]
Uuh, nice finding, will fix it thanks

**Comment by majst01** [comment]
> You downgrade containerd from 1.7.22 to 1.6.20 because you switched from `containerd.io` (Docker repository) to `containerd` (Debian repository).
> 
> Reproduce by:
> 
> ```shell
> $ docker run -it debian:bookworm
> $ apt update
> $ apt install --yes ca-certificates curl gnupg2
> $ curl -fLsS https://download.docker.com/linux/debian/gpg | apt-key add -
> $ echo "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
> $ apt update
> $ apt info containerd
> Package: containerd
> Version: 1.6.20~ds1-1+b1
> $ apt info runc
> Package: runc
> Version: 1.1.5+ds1-1+deb12u1
> $ apt info docker-ce
> Package: docker-ce
> Version: 5:27.3.1-1~debian.12~bookworm
> Priority: optional
> Section: admin
> Maintainer: Docker <support@docker.com>
> Installed-Size: 111 MB
> Depends: containerd.io (>= 1.6.24), docker-ce-cli, iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.34), libsystemd0
> Recommends: apparmor, ca-certificates, docker-ce-rootless-extras, git, libltdl7, pigz, procps, xz-utils
> Suggests: aufs-tools, cgroupfs-mount | cgroup-lite
> $ apt info containerd.io
> Package: containerd.io
> Version: 1.7.22-1
> ```

fixed now:

```
containerd --version
containerd containerd.io 1.7.22 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
```

**Review by Gerrit91 — APPROVED** [review]

**Pull request merged**
