### PR TITLE
lower tcp keepalive parameters such that connections are not dropped on firewall

### PR DESCRIPTION
**Pull request by treestructure**

### CODE REVIEW

**Review by Gerrit91 — COMMENTED** [review]
@metal-stack/metal-images-maintainers Does it make sense to add these to the Ubuntu workers as well?

**Comment by majst01** [comment]
> @metal-stack/metal-images-maintainers Does it make sense to add these to the Ubuntu workers as well?

Yes

**Comment by majst01** [comment]
I would prefer to put this into node-init, to be more flexibel

**Comment by Gerrit91** [comment]
metal-images is not the right place because these changes are too broad and not required under all circumstances. If this is required inside a Kubernetes cluster, we advise rolling out a privileged daemon set that can modify these parameters as desired.

**Pull request closed without merging**
