### PR TITLE
Add missing newline to hosts.allow

### PR DESCRIPTION
**Pull request by robertvolkmann**
Otherwise, sshd resets the connection and reports:
warning: /etc/hosts.allow, line 5: missing newline or line too long warning: /etc/hosts.allow, line 5: all the subsequent rules will be ignored

### CODE REVIEW

**Comment by majst01** [comment]
Nice, wonder how you managed to ssh to a worker ?

**Comment by robertvolkmann** [comment]
From a pod running on the worker.

**Comment by majst01** [comment]
Does not build because ubuntu mainline kernel location has moved. I will sent a separate PR.

**Comment by majst01** [comment]
Kernel location fixed in #208

**Review by majst01 — APPROVED** [review]

**Pull request merged**
